class Autogenerated {
  Data data;
  String errorMsg;
  int resultCode;

  Autogenerated({this.data, this.errorMsg, this.resultCode});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
    errorMsg = json['errorMsg'];
    resultCode = json['resultCode'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.data != null) {
      data['data'] = this.data.toJson();
    }
    data['errorMsg'] = this.errorMsg;
    data['resultCode'] = this.resultCode;
    return data;
  }
}

class Data {
  int appUserId;
  String avatarUrl;
  bool collect;
  int createdTime;
  int detailCount;
  int hot;
  int id;
  String imgUrl;
  String keyword;
  int lastTime;
  String name;
  String nickName;
  List<RankDetailList> rankDetailList;
  String remark;
  bool run;
  String scoreImgUrl;

  Data(
      {this.appUserId,
      this.avatarUrl,
      this.collect,
      this.createdTime,
      this.detailCount,
      this.hot,
      this.id,
      this.imgUrl,
      this.keyword,
      this.lastTime,
      this.name,
      this.nickName,
      this.rankDetailList,
      this.remark,
      this.run,
      this.scoreImgUrl});

  Data.fromJson(Map<String, dynamic> json) {
    appUserId = json['appUserId'];
    avatarUrl = json['avatarUrl'];
    collect = json['collect'];
    createdTime = json['createdTime'];
    detailCount = json['detailCount'];
    hot = json['hot'];
    id = json['id'];
    imgUrl = json['imgUrl'];
    keyword = json['keyword'];
    lastTime = json['lastTime'];
    name = json['name'];
    nickName = json['nickName'];
    if (json['rankDetailList'] != null) {
      rankDetailList = new List<RankDetailList>();
      json['rankDetailList'].forEach((v) {
        rankDetailList.add(new RankDetailList.fromJson(v));
      });
    }
    remark = json['remark'];
    run = json['run'];
    scoreImgUrl = json['scoreImgUrl'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['appUserId'] = this.appUserId;
    data['avatarUrl'] = this.avatarUrl;
    data['collect'] = this.collect;
    data['createdTime'] = this.createdTime;
    data['detailCount'] = this.detailCount;
    data['hot'] = this.hot;
    data['id'] = this.id;
    data['imgUrl'] = this.imgUrl;
    data['keyword'] = this.keyword;
    data['lastTime'] = this.lastTime;
    data['name'] = this.name;
    data['nickName'] = this.nickName;
    if (this.rankDetailList != null) {
      data['rankDetailList'] =
          this.rankDetailList.map((v) => v.toJson()).toList();
    }
    data['remark'] = this.remark;
    data['run'] = this.run;
    data['scoreImgUrl'] = this.scoreImgUrl;
    return data;
  }
}

class RankDetailList {
  int appUserId;
  int createdTime;
  int id;
  int lastTime;
  String name;
  int rankId;
  int score;

  RankDetailList(
      {this.appUserId,
      this.createdTime,
      this.id,
      this.lastTime,
      this.name,
      this.rankId,
      this.score});

  RankDetailList.fromJson(Map<String, dynamic> json) {
    appUserId = json['appUserId'];
    createdTime = json['createdTime'];
    id = json['id'];
    lastTime = json['lastTime'];
    name = json['name'];
    rankId = json['rankId'];
    score = json['score'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['appUserId'] = this.appUserId;
    data['createdTime'] = this.createdTime;
    data['id'] = this.id;
    data['lastTime'] = this.lastTime;
    data['name'] = this.name;
    data['rankId'] = this.rankId;
    data['score'] = this.score;
    return data;
  }
}