import 'package:bsdemo/config/service_method.dart';
import 'package:bsdemo/model/Autogenerated.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

class PageDetail extends StatefulWidget {
  Map arguments;
  PageDetail({Key key, this.arguments}) : super(key: key);

  _PageDetailState createState() => _PageDetailState(arguments:this.arguments);
}

class _PageDetailState extends State<PageDetail> {
  Map arguments;
  String title;
  _PageDetailState({this.arguments, Key key}){
    this.title = '详情';
  }

  Autogenerated _autogenerated;
 

  

   Widget _getListData(context, index) {
    return ListTile(
      title: Text(this._autogenerated.data.rankDetailList[index].name)
    );
  }

  @override
  Widget build(BuildContext context) {
    ScreenUtil.instance = ScreenUtil(width: 750, height: 1334)..init(context);
    return Scaffold(
      appBar: AppBar(
        title: Text(this.title),
      ),
      body: FutureBuilder(
        future: requestGet('detailPageContext',formData:this.arguments),
        builder: (context, snapshot){
          if(snapshot.hasData){
            this._autogenerated = Autogenerated.fromJson(snapshot.data);
  
            print(snapshot.data);
            return Column(
              crossAxisAlignment: CrossAxisAlignment.center,
              children: <Widget>[
                Image.network(this._autogenerated.data.imgUrl, fit: BoxFit.cover, width: 750.0,),
                Text(this._autogenerated.data.name),

                new Expanded(
                  child: ListView.builder(
                  itemCount: this._autogenerated.data.rankDetailList.length,
                  itemBuilder: this._getListData,
                ),
                )
                
              ],
            );
          }else {
            return Center(
              child: Text("加载中～～"),
            );
          }
        },
      ),
    );
  }
}